# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pogoda.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(530, 283))
        MainWindow.setMaximumSize(QtCore.QSize(530, 283))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_who = QtWidgets.QLabel(self.centralwidget)
        self.label_who.setGeometry(QtCore.QRect(11, 7, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_who.setFont(font)
        self.label_who.setObjectName("label_who")
        self.lineEdit_city = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_city.setGeometry(QtCore.QRect(130, 11, 391, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_city.setFont(font)
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 45, 511, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.text_out = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_out.setGeometry(QtCore.QRect(10, 80, 511, 191))
        self.text_out.setObjectName("text_out")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.lineEdit_city.editingFinished.connect(self.pushButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Погода"))
        self.label_who.setText(_translate("MainWindow", "Название города"))
        self.pushButton.setText(_translate("MainWindow", "Показать"))
